Repository cambridge-cares/TheWorldAvatar, pull requests merged in 2023-08, with the labels that each got.

#867 fix-dtvf-action
  .github/workflows/dtvf_release.yml
  .github/workflows/feature-info-agent_push.yml
  web/digital-twin-vis-framework/library/GruntFile.js
  web/digital-twin-vis-framework/library/VERSION
  web/digital-twin-vis-framework/library/release.html
Labels: bug

#868 fix-dtvf-action:
  .github/workflows/dtvf_check-version.yml
  .github/workflows/dtvf_release.yml
  .github/workflows/feature-info-agent_build.yml
  .github/workflows/feature-info-agent_push.yml
  web/digital-twin-vis-framework/CHANGELOG.md
  web/digital-twin-vis-framework/library/VERSION
Labels: bug

#858 Hotfix gdalclient database names
  Deploy/stacks/dynamic/stack-clients/docker-compose.yml
  Deploy/stacks/dynamic/stack-clients/pom.xml
  Deploy/stacks/dynamic/stack-clients/src/main/java/com/cmclinnovations/stack/clients/gdal/GDALClient.java
  Deploy/stacks/dynamic/stack-data-uploader/docker-compose.yml
  Deploy/stacks/dynamic/stack-data-uploader/pom.xml
  Deploy/stacks/dynamic/stack-manager/docker-compose.yml
  Deploy/stacks/dynamic/stack-manager/pom.xml
Labels: bug, infra-stack

#882 dev-twa-vf-docs
  web/twa-vis-framework/docs/mapbox.md
Labels: documentation

#893 Fix issue 892: Postgres runs out of free connections
  Deploy/stacks/dynamic/stack-clients/docker-compose.yml
  Deploy/stacks/dynamic/stack-clients/pom.xml
  Deploy/stacks/dynamic/stack-clients/src/main/java/com/cmclinnovations/stack/clients/geoserver/GeoServerClient.java
  Deploy/stacks/dynamic/stack-data-uploader/docker-compose.yml
  Deploy/stacks/dynamic/stack-data-uploader/pom.xml
  Deploy/stacks/dynamic/stack-manager/docker-compose.yml
  Deploy/stacks/dynamic/stack-manager/pom.xml
Labels: bug
