Repository cambridge-cares/TheWorldAvatar, pull requests merged in 2023-04, with the labels that each got.

#697 fix-feature-info-agent
  Agents/FeatureInfoAgent/Dockerfile
  Agents/FeatureInfoAgent/README.md
  Agents/FeatureInfoAgent/code/pom.xml
  Agents/FeatureInfoAgent/code/src/main/java/com/cmclinnovations/featureinfo/FeatureInfoAgent.java
  Agents/FeatureInfoAgent/code/src/main/java/com/cmclinnovations/featureinfo/kg/ClassHandler.java
  Agents/FeatureInfoAgent/code/src/main/java/com/cmclinnovations/featureinfo/kg/MetaHandler.java
  Agents/FeatureInfoAgent/code/src/main/java/com/cmclinnovations/featureinfo/kg/TimeHandler.java
  Agents/FeatureInfoAgent/code/src/test/java/com/cmclinnovations/featureinfo/FeatureInfoAgentTest.java
  Agents/FeatureInfoAgent/code/src/test/java/com/cmclinnovations/featureinfo/kg/MetaHandlerTest.java
  Agents/FeatureInfoAgent/code/src/test/java/com/cmclinnovations/featureinfo/kg/TimeHandlerTest.java
  Agents/FeatureInfoAgent/docker-compose.yml
  Agents/FeatureInfoAgent/stack-manager-input-config/feature-info-agent.json
Labels: enhancement

#696 fix-dtvf-sdf-icons
  web/digital-twin-vis-framework/example-mapbox-vis/README.md
  web/digital-twin-vis-framework/library/src/ts/mapbox/icon_handler.ts
  web/digital-twin-vis-framework/library/tsconfig.json
Labels: enhancement, visualisation

#720 212-dev-tbox-generator-command-line
  JPS_BASE_LIB/pom.xml
  JPS_BASE_LIB/src/main/java/uk/ac/cam/cares/jps/base/converter/README.md
  JPS_BASE_LIB/src/main/java/uk/ac/cam/cares/jps/base/converter/TBoxGeneration.java
Labels: enhancement, infra-base-lib
