Repository cambridge-cares/TheWorldAvatar, pull requests merged in 2024-02, with the labels that each got.

#997 Dev cities ontologies
  JPS_Ontology/ontology/ontoplanningregulation/OntoPlanningRegulation.csv
  JPS_Ontology/ontology/ontoplanningregulation/OntoPlanningRegulation.owl
  JPS_Ontology/ontology/ontoplanningregulation/README.MD
  JPS_Ontology/ontology/ontoplot/OntoPlot.csv
  JPS_Ontology/ontology/ontoplot/OntoPlot.owl
  JPS_Ontology/ontology/ontoplot/README.MD
  JPS_Ontology/ontology/ontozoning/OntoZoning.csv
  JPS_Ontology/ontology/ontozoning/OntoZoning.owl
  JPS_Ontology/ontology/ontozoning/README.MD
Labels: ontology

#1089 Cache GeoServer plugins
  Deploy/stacks/dynamic/stack-clients/docker-compose.yml
  Deploy/stacks/dynamic/stack-clients/pom.xml
  Deploy/stacks/dynamic/stack-clients/src/main/resources/com/cmclinnovations/stack/services/built-ins/geoserver.json
  Deploy/stacks/dynamic/stack-data-uploader/docker-compose.yml
  Deploy/stacks/dynamic/stack-data-uploader/pom.xml
  Deploy/stacks/dynamic/stack-manager/README.md
  Deploy/stacks/dynamic/stack-manager/docker-compose.yml
  Deploy/stacks/dynamic/stack-manager/pom.xml
Labels: enhancement

#1091 No pull Podman/Docker
  Deploy/stacks/dynamic/stack-clients/docker-compose.yml
  Deploy/stacks/dynamic/stack-clients/pom.xml
  Deploy/stacks/dynamic/stack-clients/src/main/java/com/cmclinnovations/stack/services/DockerService.java
  Deploy/stacks/dynamic/stack-clients/src/main/resources/com/cmclinnovations/stack/services/built-ins/volume-populator.json
  Deploy/stacks/dynamic/stack-data-uploader/docker-compose.yml
  Deploy/stacks/dynamic/stack-data-uploader/pom.xml
  Deploy/stacks/dynamic/stack-manager/docker-compose.yml
  Deploy/stacks/dynamic/stack-manager/pom.xml
Labels: bug, enhancement

#1100 Stack dependency fixes
  Deploy/stacks/dynamic/stack-clients/pom.xml
Labels: bug

#1102 Hotfix bump atlr dep
  Agents/utils/parent-pom/pom.xml
  Deploy/stacks/dynamic/stack-clients/docker-compose.yml
  Deploy/stacks/dynamic/stack-clients/pom.xml
  Deploy/stacks/dynamic/stack-data-uploader/docker-compose.yml
  Deploy/stacks/dynamic/stack-data-uploader/pom.xml
  Deploy/stacks/dynamic/stack-manager/docker-compose.yml
  Deploy/stacks/dynamic/stack-manager/pom.xml
Labels: bug

#1108 OntoUBEMMP documentation
  JPS_Ontology/ontology/ontoubemmp/README.md
Labels: documentation
